spring:
  profiles: dev
  
rootPath: ./temp/

---

spring:
  profiles: prod
  
rootPath: /opt/

--- 
spring:
  profiles: test
  
rootPath: ./tests/fixtures/

--- 

spring:

  profiles:    active:    - prod

  datasource:
    url: jdbc:mysql://localhost:3306/toast?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: DEBUG
