spring:
  profiles: default

  datasource:
    url: jdbc:mysql://localhost:3306/toast?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: DEBUG

# Dev env
---

spring:
  profiles: dev, default
  
io:
  toast:
    rootPath: ./temp/

# Test env
---
spring:
  profiles: test, default
  
io:
  toast:
    rootPath: ./tests/fixtures/

# Production env
--- 

spring:
  profiles: prod, default

io:
  toast:
    rootPath: /opt/ 
