spring:
  profiles:
    active: test

  datasource:
    url: jdbc:mysql://localhost:3306/toast?createDatabaseIfNotExist=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;characterSetResults=UTF-8

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: DEBUG

# Dev env
---

spring:
  profiles: dev

io:
  toast:
    rootPath: ./temp/

# Production env
---

spring:
  profiles: prod

io:
  toast:
    rootPath: /opt/

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

# Test env
---
spring:
  profiles: test

io:
  toast:
    rootPath: ./tests/fixtures/
