spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/toast?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: DEBUG

# Test env
---
spring:
  profiles: test
  
io:
  toast:
    rootPath: ./tests/fixtures/

# Production env
--- 

spring:
  profiles: prod

io:
  toast:
    rootPath: /opt/ 

# Dev env
---

spring:
  profiles: dev

io:
  toast:
    rootPath: ./temp/
